### ISSUE TITLE
Number of Plots to create

### ISSUE THREAD

**Issue by Drhicom** [stotiks/chia-plot-manager#4]
Please increase the number of plots to make 

![2024-02-01_145835](https://github.com/stotiks/chia-plot-manager/assets/81637574/ea81b1b7-d484-4211-91d4-915e57077d7f)
If connected 4 disks and making K32C19 the number is 1188 plots.

Thank you

**Comment by stotiks** [comment]
Fixed [v0.2.1](https://github.com/stotiks/chia-plot-manager/releases/tag/v0.2.1)

**Comment by Drhicom** [comment]
Thank you
