### ISSUE TITLE
Plot manager 2.5 doesn't allow for C29 plots

### ISSUE THREAD

**Issue by Drhicom** [stotiks/chia-plot-manager#6]
When Max released the version of cuda_plot_k32_v3 to allow C29 plots it didn't make it into this release of plot manager 2.5.
.
![image](https://github.com/stotiks/chia-plot-manager/assets/81637574/52e2e3fe-9dc1-4939-b852-faa3ff743902)

thank you for your support.

Roy

**Comment by stotiks** [comment]
Fixed

**Comment by Drhicom** [comment]
Thank you sir
![image](https://github.com/stotiks/chia-plot-manager/assets/81637574/91fb99b6-0e36-47ff-8890-32522c5fadba)
